"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Virtuals',
 'project_name': 'Commerce Identity Fabric',
 'track': 'Virtuals',
 'pitch': 'An identity fabric that maps agent personas, permissions, and payment '
          'surfaces into one reusable commerce and delegation layer.',
 'idea_titles': ['ERC-8183 Agent Identity Layer',
                 'ENS-Native Agent Commerce',
                 'ZK-Protected Persona Wallets'],
 'architecture_summary': 'An identity fabric maps agent personas, permissions, and '
                         'payment surfaces into one reusable layer. The contract '
                         'records identity state and trust anchors, while Python '
                         'orchestration ties those identities to commerce and '
                         'delegation flows.',
 'overlap_targets': ['ENS',
                     'Slice',
                     'SelfProtocol',
                     'ERC-8004 Receipts',
                     'PayWithLocus',
                     'SuperRare'],
 'primary_contract_name': 'CommerceIdentityRegistry',
 'primary_python_module': 'virtuals_fabric',
 'category': 'identity',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'identity_state',
                       'description': 'Names, wallets, manifests, and verification '
                                      'proofs.'},
                      {'name': 'permissions',
                       'description': 'Which principals can act on which rails.'},
                      {'name': 'reputation_events',
                       'description': 'Receipts, scores, and attestation updates.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and public evidence links.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for CommerceIdentityRegistry.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'virtuals_fabric.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Virtuals',
               'docs_url': 'https://www.virtuals.io/',
               'env_vars': ['VIRTUALS_API_URL'],
               'endpoint_env': 'VIRTUALS_API_URL',
               'action_kind': 'rest_json',
               'purpose': 'Sync agent personas and commerce-facing identity metadata.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Slice',
               'docs_url': 'https://docs.slice.so/',
               'env_vars': ['SLICE_API_KEY', 'SLICE_HOOK_URL'],
               'endpoint_env': 'SLICE_HOOK_URL',
               'action_kind': 'rest_json',
               'purpose': 'Drive checkout hooks and storefront policy changes.'},
              {'name': 'SelfProtocol',
               'docs_url': 'https://docs.self.xyz/',
               'env_vars': ['SELF_PROTOCOL_API_KEY', 'SELF_VERIFICATION_URL'],
               'endpoint_env': 'SELF_VERIFICATION_URL',
               'action_kind': 'rest_json',
               'purpose': 'Gate sensitive actions behind privacy-preserving proofs.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'SuperRare',
               'docs_url': 'https://superrare.com/',
               'env_vars': ['SUPERRARE_API_KEY', 'SUPERRARE_MINT_URL'],
               'endpoint_env': 'SUPERRARE_MINT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Mint art-series media and auction metadata.'}],
 'actions': [{'id': 'virtuals_identity_sync',
              'target': 'virtuals',
              'purpose': 'Use Virtuals for a bounded action in this repo.',
              'partner': 'Virtuals',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Virtuals only after a dry-run artifact exists.',
                        'Use https://www.virtuals.io/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 95,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'slice_checkout_hook',
              'target': 'slice',
              'purpose': 'Use Slice for a bounded action in this repo.',
              'partner': 'Slice',
              'action_kind': 'rest_json',
              'max_amount_usd': 35,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Slice only after a dry-run artifact exists.',
                        'Use https://docs.slice.so/ for credential setup.']},
             {'id': 'selfprotocol_zk_verify',
              'target': 'selfprotocol',
              'purpose': 'Use SelfProtocol for a bounded action in this repo.',
              'partner': 'SelfProtocol',
              'action_kind': 'rest_json',
              'max_amount_usd': 3,
              'priority': 85,
              'sensitivity': 'high',
              'notes': ['Call SelfProtocol only after a dry-run artifact exists.',
                        'Use https://docs.self.xyz/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'superrare_mint_series',
              'target': 'superrare',
              'purpose': 'Use SuperRare for a bounded action in this repo.',
              'partner': 'SuperRare',
              'action_kind': 'rest_json',
              'max_amount_usd': 40,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call SuperRare only after a dry-run artifact exists.',
                        'Use https://superrare.com/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
